services:
  db2:
    ports:
      - "3306:3306"
    volumes:
      - logs:/var/log/mysql

  api:
    image: makeradmin/api-dev:1.0
    volumes:
      - ./api/src:/work/src
      - logs:/work/logs
    ports:
      - "8010:80"
    environment:
      DEV_RUN: "true"
      TEST_SERVICE_TOKEN:

  email-dispatcher:
    image: makeradmin/api-dev:1.0
    volumes:
      - ./api/src:/work/src

#  accessy-syncer:
#    image: makeradmin/api-dev:1.0
#    volumes:
#      - ./api/src:/work/src

  public:
    image: makeradmin/public-dev:1.0
    build:
      args:
        DEV_BUILD: "true"
    ports:
      - "8011:80"
    volumes:
      - ./public/ts:/work/ts
      - ./public/scss:/work/scss
      - ./public/src:/work/src
    environment:
      DEV_RUN: "true"

  admin:
    image: makeradmin/admin-dev:1.0
    build:
      dockerfile: DevServerDockerfile
    ports:
      - "8009:80"
    volumes:
      - ./admin/src:/work/src
      - ./admin/dist:/work/dist

volumes:
  logs:
